name: ben1212docker

trigger:
- main
#- feature/*

pool: Docker
  #vmImage: ubuntu-latest


variables:
  - group: Staging Variables

stages:

# Continuous Integration Process
- stage: CI
  jobs:
  - job: BuildAndPushDocker
    workspace: 
      clean: all
    steps:
      - task: DockerInstaller@0
        inputs:
          dockerVersion: '17.09.0-ce'
      - task: Docker@2
        inputs:
          containerRegistry: 'ben1212docker.azurecr.io'
          repository: 'weight-app-repository'
          command: 'buildAndPush'
          Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'


# Continuous Deployment Process for Staging Environment
# - stage: DeployToStaging
#   condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
#   jobs:
#   - deployment: staging
#     displayName: Deploy to Staging
#     environment:
#       name: "dockhost000001"
#       resourceType: VirtualMachine

#     strategy:
#       runOnce:
#         deploy:
#           steps:
          

# Continuous Delivery Process for Production Environment


# - stage: DeployToProduction
#   condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
#   jobs:
#       - deployment: production
#         displayName: Deploy to Production
#         environment:
#           name: <<YOUR ENVIRONMENT NAME>>
#           resourceType: VirtualMachine
#         strategy:
#           runOnce:
#             deploy:
#               steps:
              